firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('genre/',include('genre.urls')),
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

firstproject/genre/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #/genre/
    path('',views.index.as_view(),name='index'),

    #/genre/1/
    path('<int:pk>/',views.details.as_view(),name='details'),

    # register/
    path('register/', views.UserFormView.as_view(), name='userform'),
    

]

firstproject/genre/models.py
from django.db import models

class Collection(models.Model):
    collection_name = models.CharField(max_length=100)
    description = models.CharField(max_length=500)
    collcover = models.CharField(max_length=100)

    def __str__(self):
        return self.collection_name
        


class Piece(models.Model):
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    typ = models.CharField(max_length=200)
    artist = models.CharField(max_length=200)
    year = models.IntegerField()
    piececover = models.CharField(max_length=1000)

    def __str__(self):
        
        return self.title

firstproject/genre/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'email', 'password']

firstproject/genre/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Collection, Piece
from django.views import generic
from .forms import UserForm
from django.contrib.auth import authenticate, login
from django.views.generic import View

class index(generic.ListView):
    template_name = 'genre/genretemplate.html'

    def get_queryset(self):
        return Collection.objects.all()
        
        

# def index(request):
#     all_collections = Collection.objects.all()
#     context={
#         "all_collections":all_collections
#     }
#     return render(request, "genre/genretemplate.html",context)


class details(generic.DetailView):
    model = Collection
    template_name = 'genre/detailtemplate.html'



# def details(request,genre_id):
#     collection_item = Collection.objects.get(pk=genre_id)
#     piece_item = Piece.objects.filter(collection=collection_item)
#     context = {
#         "Pitem" : piece_item
#     }
#     return render(request, "genre/detailtemplate.html",context)


class UserFormView(View):
    form_class = UserForm
    template_name = 'genre/formtemplate.html'

    def get(self, request):
        form= self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            newuser = authenticate(username=username, password=password)

            if newuser is not None:

                if newuser.is_active:
                    login(request, newuser)
                    return redirect('/genre')
        return render(request, self.template_name, {'form': form})

firstproject/genre/templates/genre/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Navigation Bar</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/genre">Home</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/genre/register">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">{{ request.user }}</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %} {% endblock %}
  </body>
</html>

firstproject/genre/templates/genre/detailtemplate.html
<!DOCTYPE html>
{% extends 'genre/base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
{% block content %}
    {% for piece_obj in collection.piece_set.all %}
    <div align="center">
        <img src="{{piece_obj.piececover}}" height="200px" width="200px" alt="">
        <h2>{{pieceobj.title}}- By {{piece_obj.artist}}</h2>
        <h3>{{piece_obj.typ}}</h3>
        <h3>{{piece_obj.year}}</h3>
        <br>
    </div>
    {% endfor %}

{% endblock %}
</body>
</html>

firstproject/genre/templates/genre/formtemplate.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Registration</title>
        {% extends 'genre/base.html' %}
</head>
<body>
    {% block content %}
        <form action="" method="post">
            {% csrf_token %}
            
            <label for="username">username</label>
            <input type="text" name="username">
            <br>
            <label for="email">Email: </label>
            <input type="email" name="email">
            <br>
            <label for="password">Password: </label>
            <input type="password" name="password">    
            <br>

            <input type="submit" value="Register">
        </form>


    {% endblock %}
    
</body>
</html>

firstproject/genre/templates/genre/genretemplate.html
<!DOCTYPE html>

{% extends 'genre/base.html' %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Genre</title>
</head>
<body>

{% block content %}
    {% for genreobj in object_list %}
    <div align="center">
        <img src="{{genreobj.collcover}}" height="200px" width="200px" alt="">
        <h2><a href="/genre/{{genreobj.id}}/">{{genreobj.collection_name}}</a></h2>
        <h3>{{genreobj.description}}</h3>
        <br>
    </div>
    {% endfor %}

{% endblock %}

</body>
</html>